# .github/workflows/build.yml
name: Build Kodi Repo

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and publish Kodi repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Create folders
        run: |
          mkdir -p repo
          mkdir -p zips

      - name: Download addon zips
        run: |
          wget -O zips/plugin.video.mercadoplay.zip https://github.com/wetdreams69/plugin.video.mercadoplay/raw/master/plugin.video.mercadoplay.zip
          wget -O zips/plugin.video.youtubemovieslatino.zip https://github.com/wetdreams69/plugin.video.youtubemovieslatino/raw/main/plugin.video.youtubemovieslatino.zip
          wget -O zips/plugin.video.robinhood.zip https://github.com/wetdreams69/plugin.video.robinhood/raw/master/plugin.video.robinhood.zip

      - name: Unzip addons and extract addon.xml
        run: |
          for zip in zips/*.zip; do
            unzip -o "$zip" -d repo/
          done

      - name: Generate addons.xml and md5
        run: |
          echo "<addons>" > repo/addons.xml
          find repo -name addon.xml | while read addon; do
            cat "$addon" | tr -d '\n' >> repo/addons.xml
          done
          echo "</addons>" >> repo/addons.xml
          md5sum repo/addons.xml | cut -d ' ' -f1 > repo/addons.xml.md5

      - name: Copy zips to repo
        run: |
          cp zips/*.zip repo/
